name: CI/CD

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

# Add default permissions at workflow level (most restrictive)
permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    # This job only needs read permissions
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        if: success()

      - name: Setup Node.js
        if: success()
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        if: success()
        run: npm ci

      - name: Run tests
        if: success()
        run: npm run test:ci

      - name: Build
        if: success()
        run: npm run build

      - name: Upload build output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            public
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    # Deploy job needs write permissions for deployments
    permissions:
      contents: read
      deployments: write
    if: success() && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') || (github.event_name == 'pull_request' && github.base_ref == 'dev'))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Deploy to Vercel
        continue-on-error: true
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/main' ]]; then
            env="production"
            env_opt="--prod"
          elif [[ ${{ github.event_name }} == 'push' && ${{ github.ref }} == 'refs/heads/dev' ]]; then
            env="development"
          else
            env="preview"
          fi
          token_opt="--token=$VERCEL_TOKEN"
          npx vercel pull --yes --environment=$env $token_opt
          NEXT_TELEMETRY_DISABLED=1 npx vercel build $env_opt $token_opt --cwd .
          npx vercel deploy $env_opt $token_opt --prebuilt
